---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: github-deployment-resource
  path: gopath/src/github.com/ahume/github-deployment-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/ahume/github-deployment-resource/scripts/ci
